name: Backend CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Set up Java 17
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker build -t ruoyi-stg:${{ github.ref_name }} .
          docker tag ruoyi-stg:${{ github.ref_name }} 555066174866.dkr.ecr.ap-northeast-1.amazonaws.com/ruoyi-stg-ruoyi:${{ github.ref_name }}

      - name: Configure AWS credentials
        if: startsWith(github.ref, 'refs/tags/v')
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::555066174866:role/GitHubActions-RuoYi-ECR-Role
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        if: startsWith(github.ref, 'refs/tags/v')
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker push 555066174866.dkr.ecr.ap-northeast-1.amazonaws.com/ruoyi-stg-ruoyi:${{ github.ref_name }}